version: "3.7"

services:
  fastapp:
    build: fastapi
    ports:
      - 8000:8000
    networks:
      goalnetwork:
        aliases:
          - fastapi.docker
  streamlit:
    build: streamlit
    ports:
      - 8501:8501
    depends_on:
      - fastapp
    networks:
      goalnetwork:
        aliases:
          - streamlit.docker
networks:
  buurten:
    external:
      name: "buurtnetwork"